-- to run this file use:
-- psql --file=excluded.sql stx
INSERT INTO excludes VALUES ('DUST') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('ERY') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('FAZ') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('SOXS') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('SDOW') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('SPXS') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('SPXU') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('SQQQ') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('SRTY') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('SVXY') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('TECS') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('TZA') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('UVXY') ON CONFLICT DO NOTHING;
INSERT INTO excludes VALUES ('VXX') ON CONFLICT DO NOTHING;
